"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { EvaluationDisplay } from "@/components/evaluation-display";
import { useLearnerContext } from "@/components/learner-context";
import { type AgentTurnResponse, type PracticeResponse, type WritingEvaluationResponse, apiClient } from "@/lib/api/client";
import { presentAgentStep, presentAgentStopReason } from "@/lib/agent-presentation";
import { isSubmissionConflictLocked, presentApiError, skillLabels } from "@/lib/presentation";

export default function PracticePage() {
 const params=useParams<{practiceId:string}>(); const router=useRouter(); const {cache,isReady,setRecommendation}=useLearnerContext();
 const [practice,setPractice]=useState<PracticeResponse|null>(null); const [agentTurn,setAgentTurn]=useState<AgentTurnResponse|null>(null); const [essay,setEssay]=useState(""); const [evaluation,setEvaluation]=useState<WritingEvaluationResponse|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [conflict,setConflict]=useState(false);
 const practiceId=Number(params.practiceId); const learnerId=cache?.currentLearnerId??null;
 const load=useCallback(async()=>{ if(learnerId===null||!Number.isInteger(practiceId)||practiceId<=0)return; setBusy(true);setError(null);try{const item=await apiClient.getPractice(learnerId,practiceId);setPractice(item);if(item.lifecycle_state==="submitted")setEvaluation(await apiClient.getPracticeEvaluation(learnerId,practiceId));else setEvaluation(null);}catch(reason){setError(presentApiError(reason));}finally{setBusy(false);}},[learnerId,practiceId]);
 useEffect(()=>{const timer=window.setTimeout(()=>{if(isReady)void load();},0);return()=>window.clearTimeout(timer);},[isReady,load]);
 async function submit(){if(learnerId===null||essay.trim()==="")return;setBusy(true);setError(null);setConflict(false);try{const result=await apiClient.agentTurn(learnerId,{turn_type:"practice_submission",practice_id:practiceId,essay});setAgentTurn(result);if(result.stop_reason==="submission_conflict"){setConflict(true);return;}const nextPractice=result.current_practice;if(nextPractice!==null&&nextPractice.id!==practiceId){router.push(`/practice/${nextPractice.id}`);return;}await load();}catch(reason){setError(presentApiError(reason));}finally{setBusy(false);}}
 async function complete(){if(learnerId===null||evaluation===null)return;setBusy(true);try{const result=await apiClient.completePractice(learnerId,practiceId);setRecommendation(result.next_recommendation_id,result.next_recommendation);router.push("/dashboard");}catch(reason){setError(presentApiError(reason));}finally{setBusy(false);}}
 if(!isReady)return <p className="status-copy" aria-live="polite">正在恢复学习进度…</p>; if(cache===null)return <section className="content-card"><Link className="primary-action" href="/setup">前往学习设置</Link></section>; if(practice===null)return <p className="status-copy" aria-live="polite">{error??"正在读取练习…"}</p>;
 const submitted=practice.lifecycle_state==="submitted"; const processing=practice.lifecycle_state==="submission_in_progress";
 return <section className="writing-page"><p className="eyebrow">针对性练习</p><h1>{practice.focus_objective}</h1><p className="supporting-copy">训练重点：{skillLabels[practice.target_skill]}</p><article className="content-card"><h2>Writing Task 2</h2><p className="question-copy">{practice.question}</p><h3>写作提示</h3><ul>{practice.instructions.map(x=><li key={x}>{x}</li>)}</ul><h3>检查清单</h3><ul>{practice.checkpoints.map(x=><li key={x}>{x}</li>)}</ul></article>{agentTurn&&<section className="content-card" aria-live="polite"><p>学习助手状态：{presentAgentStopReason(agentTurn.stop_reason)}</p><ol>{agentTurn.steps.map((step,index)=><li key={`${step.tool}-${index}`}>{presentAgentStep(step.tool,step.outcome)}</li>)}</ol></section>}{error&&<p className="error-message" role="alert">{error}</p>}{isSubmissionConflictLocked(conflict ? "conflict" : null)?<section className="content-card next-step"><p className="error-message">此练习已提交过不同作文，不能覆盖或继续完成。</p><button className="primary-action" onClick={()=>{setConflict(false);void load();}} type="button">重新读取练习状态</button></section>:processing?<section className="content-card next-step"><p className="status-copy">作文正在处理中，请稍后重新检查。</p><button className="primary-action" onClick={()=>void load()} type="button">刷新练习状态</button></section>:!submitted?<section className="content-card next-step"><label htmlFor="practice-essay">你的英文作文</label><textarea id="practice-essay" value={essay} onChange={e=>setEssay(e.target.value)}/><button className="primary-action" disabled={busy||essay.trim()===""} onClick={submit} type="button">{busy?"正在提交…":"提交作文并由学习助手继续"}</button></section>:<section className="content-card next-step"><p className="status-copy">该练习已提交，正在恢复持久化评估。</p></section>}{evaluation&&<><EvaluationDisplay evaluation={evaluation.evaluation}/><button className="primary-action" disabled={busy} onClick={complete} type="button">完成练习并获取下一步建议</button></>}</section>;
}